### ISSUE TITLE
How to get my updated mbx script before Rob pulls it

### ISSUE THREAD

**Issue by daverosoff** [ladanielson/MAT101#7]
I was going to write a bunch of complicated git instructions, but do this instead:

Visit [the raw version of my revision of the `mbx` script](https://raw.githubusercontent.com/daverosoff/mathbook/update-windows/script/mbx) and copy the entire thing. Replace your file

```
/c/GitHubFiles/mathbook/user/mbx
```

with the text you just copied (replace the whole thing). You might want to back up your copy first:

```
cp /c/GitHubFiles/mathbook/user/mbx /c/GitHubFiles/mathbook/user/mbx.bak
```

Then try to build the images and let me know what happens! If everything seems to work nicely, including the cropping and the images are not blurry, then you should close the issue.

**Comment by ladanielson** [comment]
I have beautiful svg images!!!!!!!!
