### ISSUE TITLE
How to restrict the mbx script to a subtree

### ISSUE THREAD

**Issue by daverosoff** [ladanielson/MAT101#8]
If you add another flag `-r` to your `mbx` command, you can restrict so that you don't have to recompile all the images. Say you just worked on

```
<image xml:id="my-cool-image">
    <latex-image-code>
        ...
    </latex-image-code>
</image>
```

and you want to see how it looks in the SVG. Do this:

```
/path/to/mbx -vv -c latex-image -f svg -d images -r my-cool-image /path/to/index.mbx
```

You can use `@xml:id` of a chapter, section, etc., to just process the images in that subdivision.

**Comment by ladanielson** [comment]
Thanks!
